sonar.projectKey=aqibdev01_devops-project
sonar.organization=aqibdev01
sonar.projectName=devops-project
sonar.projectVersion=1.0
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
